version: 0.2
phases:
  install:
    commands:
      - pip install mypy

  build:
    commands:
      - cd src/lambda_func_1
      - docker build -t lambda-func-1 .

environment:
  buildImage: aws/codebuild/docker:18.09.0