version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install mypy isort

  pre_build:
    commands:
      - echo "Running linters..."
      - chmod +x script.sh
      - set +e
      - ./script.sh
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -r deployment_package.zip . -x "buildspec.yml" "README.md"
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name terraform-demo-func --zip-file fileb://deployment_package.zip
      - echo "DONE!!"
