version: 0.2
phases:
  install:
    commands:
      - pip install mypy

  build:
    commands:
      - pwd  # Print the current working directory
      - ls   # List the files in the current directory
      - git --version  # Check the Git version
      - git status
      - echo 1
      - echo $(git diff-tree --name-only -r --no-commit-id HEAD)
      - chmod +x script.sh
      - ./script.sh

#  post_build:
#    commands:
#      - $(aws ecr get-login --no-include-email --region eu-central-1)
#      - docker tag lambda-func-1 764717859735.dkr.ecr.eu-central-1.amazonaws.com/lambda-func-1:latest
#      - docker push 764717859735.dkr.ecr.eu-central-1.amazonaws.com/lambda-func-1:latest
#
