version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
      python: 3.8
    commands:
      - pip install mypy

  build:
    runtime-versions:
      docker: 18
    commands:
      - cd src/lambda_func_1
      - docker build -t lambda-func-1 .

environment:
  buildImage: aws/codebuild/docker:18.09.0