version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install mypy isort flake8

  pre_build:
    commands:
      - echo "Running linters..."
      - chmod +x script.sh
#      - ./script.sh
  build:
    commands:
      - pip install -r requirements.txt -t ./dependencies
      - echo "Zipping deployment package..."
      - zip -r deployment_package.zip . -x "buildspec.yml" "README.md"
      - cd dependencies && zip -r ../deployment_package.zip .
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name terraform-demo-func --zip-file fileb://deployment_package.zip
      - echo "DONE!!"
