version: 0.2
phases:
  install:
    commands:
      - pip install mypy

  build:
    commands:
      - funcs[0]="lambda_func_1" &&
        funcs[1]="lambda_func_2" &&
        str="src/lambda_func_1/app.py src/lambda_func_2/app.py" &&

        for func in "${funcs[@]}"; do &&
        if [[ $str =~ func ]]; then &&
          docker build -t lambda-func-1 . &&
          $(aws ecr get-login --no-include-email --region eu-central-1) &&
          docker tag lambda-func-1 764717859735.dkr.ecr.eu-central-1.amazonaws.com/lambda-func-1:latest &&
          docker push 764717859735.dkr.ecr.eu-central-1.amazonaws.com/lambda-func-1:latest
        fi &&
        done

#  post_build:
#    commands:
#      - $(aws ecr get-login --no-include-email --region eu-central-1)
#      - docker tag lambda-func-1 764717859735.dkr.ecr.eu-central-1.amazonaws.com/lambda-func-1:latest
#      - docker push 764717859735.dkr.ecr.eu-central-1.amazonaws.com/lambda-func-1:latest
#
